[workspace]
resolver = "2"
members = [ "bakkie", "bakkie_derive", "bakkie_schema", "examples/basic", "gen"]

[patch.crates-io]
bakkie = { path = "bakkie" }
bakkie_schema = { path = "bakkie_schema" }
bakkie_derive = { path = "bakkie_derive" }
